### ISSUE TITLE
Feature request: Options Orders

### ISSUE THREAD

**Issue by chandrab** [jessecooper/pyetrade#13]
Any possibility of getting the ability to place option orders (puts, calls etc.) into Etrade via PyEtrade?

**Comment by jessecooper** [comment]
It is in the TODOs but no eta at this time. Contribution is always very welcome. Still trying to get all the old stuff from v0 over to v1. That is almost complete after that I'll look at adding new features.

**Comment by hz2018tv** [comment]
I am not using pytrade, but I am seeing a problem with options order. PreviewOrderRequest on equities are much more reliable, but on options sometimes it works ok and lots of times I got "(u'code', u'100'), (u'message', u'The requested service is not currently available, please try after sometime.')", Found this repo while searching for hints.

**Comment by dmcrider** [comment]
I come from a C# background, but ETrade doesn't support C#. I've played around with python in the past so I can give this a try this weekend. I found an example for an option preview and place order request that looks promising. I'll get familiar with this project and see if I can't have something going for options sometime next week.

**Comment by jessecooper** [comment]
@dmcrider please reach out if you have any questions. I look forward to seeing the PR.

**Comment by shan23** [comment]
Ouch - I adopted pyetrade in my code and after the ENTIRE weekend, found out that the only thing I wanted (buy/sell options) isn't supported. Since I'd have to do it anyways on my own, do you have any tips @jessecooper about re-using some of the code you must've already written for EQUITY orders ?

**Comment by jessecooper** [comment]
https://github.com/jessecooper/pyetrade/blob/master/pyetrade/order.py

This area of code need to be revisited to be more inline with the v1 api. Instead of the method being `place_equity_order` it really should just be `place_order`. I have not tested this but since `place_equity_order` takes `**kwargs` you might be able to use it for options anyway. 

https://apisb.etrade.com/docs/api/order/api-order-v1.html#/definition/orderPlace

In the future the `ETradeOrders` methods should be:

- list_orders
- preview_order
- place_order
- cancel_order
- change_previewed_order
- place_changed_order

These should work for equity, option, etc.. orders and sadly use XML as the default return given the json APIs issues in the past but should still provide the json option like the current accounts.py module:
https://github.com/jessecooper/pyetrade/blob/master/pyetrade/accounts.py

all method returns should be a dict. 

I think this would be the best way to handle this and would keep it in line with the API.

**Comment by shan23** [comment]
@jessecooper I'm halfway there in the implementation - sharing some thoughts about your suggestion. I strongly feel that conflating an option order and an equity order in the API would be a mistake. There are parts which are similar but parts which are starkly different, and having to always check (if option_order do_this else do_that) is going to make the code unreadable and increase the cyclotomic complexity to unmanageable levels. Hence, so far I've done the following:
* place_option_order
* check_option_order

By the way, did you ever go back and check if the Trade bug that required you to *always* preview an order before placing it had been addressed ? I'm designing a real-time trading system, and it would be maddening to always have to do two expensive calls to Trade in market hours instead of the just one kill-or-fill order.

**Comment by shan23** [comment]
> @jessecooper I'm halfway there in the implementation - sharing some thoughts about your suggestion. I strongly feel that conflating an option order and an equity order in the API would be a mistake. There are parts which are similar but parts which are starkly different, and having to always check (if option_order do_this else do_that) is going to make the code unreadable and increase the cyclotomic complexity to unmanageable levels. Hence, so far I've done the following:
> 
> * place_option_order
> * check_option_order
> 
> By the way, did you ever go back and check if the Trade bug that required you to _always_ preview an order before placing it had been addressed ? I'm designing a real-time trading system, and it would be maddening to always have to do two expensive calls to Trade in market hours instead of the just one kill-or-fill order.

Just checked - at least for options orders, that's still the case :(

**Comment by jessecooper** [comment]
@shan23 I agree that could get messy. I am fine with splitting it out.

**Comment by kevinrider** [comment]
If you are still working on implementing option orders for pyetrade my phpetrade repo gives some examples for 1, 2, and 4 legged option orders written in php.
https://github.com/kevinrider/phpetrade
There are some errors in the ETrade API docs and the phpetrade code examples give the XML format that works consistently with PreviewOrderRequest and PlaceOrderRequest in a production environment.

**Comment by rickbricker** [comment]
> @jessecooper I'm halfway there in the implementation - sharing some thoughts about your suggestion. I strongly feel that conflating an option order and an equity order in the API would be a mistake. There are parts which are similar but parts which are starkly different, and having to always check (if option_order do_this else do_that) is going to make the code unreadable and increase the cyclotomic complexity to unmanageable levels. Hence, so far I've done the following:
> 
> * place_option_order
> * check_option_order
> 
> By the way, did you ever go back and check if the Trade bug that required you to _always_ preview an order before placing it had been addressed ? I'm designing a real-time trading system, and it would be maddening to always have to do two expensive calls to Trade in market hours instead of the just one kill-or-fill order.

@shan23 Did you ever figure out how to implement this? If so it would be doing the all of us a favor if you could post your solution. I for one would be incredibly grateful because I'm trying to figure this out now.

**Comment by IV2KBMoFxYIA** [comment]
@shan23 i guess you gave up on this? any change of trying again?

**Comment by mw66** [comment]
@shan23 can you create a PR of what you have worked out so far? So other people can continue working on what you got, instead of starting from scratch?

Thanks!
