### ISSUE TITLE
Please add usage examples

### ISSUE THREAD

**Issue by bionicles** [jessecooper/pyetrade#19]
The docs are fairly thorough on the API, but there is nothing about how to actually use this to accomplish typical goals (login, get balance, get ticker price, get moving average, place an order)

this repo will be 100x more valuable with just 1 simple example in the readme

**Comment by jessecooper** [comment]
The README has an example. In fact, it just got updated. Also, I'm always happy to accept PRs.

**Comment by rickbricker** [comment]
Hi, just came across this awesome wrapper. I am also a little confused - I know this issue is closed, but it would be nice to have an example of how to place an order. There are indeed examples of other things in the docs, but I didn't find a specific example showing how to place an order. Thanks again for all the work you've done on this!
