### ISSUE TITLE
Automatic Authentication

### ISSUE THREAD

**Issue by samjohnson1357** [jessecooper/pyetrade#63]
When you authenticate it requires you to manually open up the E*TRADE website to obtain a code.  Is there any way to automate this so that my trading strategy can run without me being there to start it up?  I might be missing something obvious.  Please help.

**Comment by jessecooper** [comment]
This could be a good topic for the [Discussions](https://github.com/jessecooper/pyetrade/discussions) if you would like to start it. I know different people have different strategies around this. This is something that will never be directly in PyEtrade because it is outside of the scope of the API and is better implemented in the application that leverages PyEtrade but still good to have a good Discussion section on because it has been asked about a few times.

**Comment by samjohnson1357** [comment]
Okay, thanks.
